image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - dockerize
  - deploy

variables:
  DOCKER_IMAGE_NAME: huyenthai01/chat-service
  PROJECT_PATH: src/ChatService/ChatService.csproj
  TEST_PATH: src/ChatService.Tests/ChatService.Tests.csproj
  TAG_NAME: latest

before_script:
  - dotnet restore

build:
  stage: build
  tags:
    - project

  script:
    - dotnet build $PROJECT_PATH --configuration Release

test:
  stage: test
  tags:
    - project

  script:
    - dotnet test $TEST_PATH --configuration Release 


dockerize:
  stage: dockerize
  tags:
    - project
  image: docker:latest
  services:
    - docker:dind
  script:
    - $tag1 = "${env:DOCKER_IMAGE_NAME}:${env:CI_COMMIT_SHORT_SHA}"
    - $tag2 = "${env:DOCKER_IMAGE_NAME}:${env:TAG_NAME}"
    - $context = "${env:CI_PROJECT_DIR}"
    - docker build -t $tag1 -t $tag2 $context
  only:
    - branches





deploy:
  stage: deploy
  tags:
    - project
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "${env:DOCKER_HUB_PASSWORD}" | docker login -u "${env:DOCKER_HUB_USERNAME}" --password-stdin
    - docker push ${env:DOCKER_IMAGE_NAME}:${env:CI_COMMIT_SHORT_SHA}
    - docker push ${env:DOCKER_IMAGE_NAME}:${env:TAG_NAME}
  only:
    - branches
